### ISSUE TITLE
As an Open Data Hub Analytics v2 maintainer I want to host the application on our servers in order to begin testing them

### ISSUE THREAD

**Issue by clezag** [noi-techpark/opendatahub-analytics-v2#7]
- [x] REUSE
- [x] CI/CD (similar to https://github.com/noi-techpark/it.bz.opendatahub.databrowser)
- [x] Keycloak integration
- [x]  DNS/Proxy

Demo URL: https://analytics.beta.dev.testingmachine.eu/

**Comment by luhodaan** [comment]
@rcavaliere, la repository necessita di documentazione per il processo di build, altrimenti sono fermo nella issue. Sarebbe necessario richiedere se sei d'accordo:

1. Un file README.md completo contenente:
   - Prerequisiti di sistema
   - Istruzioni dettagliate per il build

2. File di containerizzazione:
   - Dockerfile
   - docker-compose.yml

Questo ci permetterebbe di:
- Verificare il corretto funzionamento dell'applicazione in ambiente isolato
- Procedere rapidamente con l'implementazione della CI/CD
- Configurare il deployment sui nostri sistemi

**Comment by rcavaliere** [comment]
@luhodaan ok, I ask the supplier directly in the PR, put you in CC

**Comment by luhodaan** [comment]
@rcavaliere now you can find the application hosted at [this link](https://analytics.beta.dev.testingmachine.eu/).
Thank you

**Comment by rcavaliere** [comment]
@luhodaan nice work, thank you! The prototype looks good, even if there is still a lot to be completed.
